In [1]:
pip install numpy pandas openpyxl sqlalchemy pymysql

Requirement already satisfied: numpy in c:\users\harsh\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: pandas in c:\users\harsh\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\harsh\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\harsh\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harsh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\harsh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harsh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\harsh\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\harsh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Step 1 : Import required Libraries
import pandas as pd 
import numpy as np

In [3]:
# Load Dataset 
df = pd.read_excel('Ecommerce_Unclean_Project.xlsx')

In [4]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [6]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [8]:
# Data Shape
df.shape

(524, 15)

In [10]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(11)

In [13]:
# Remove Duplicates 
df.drop_duplicates(inplace = True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
# step 6 : Replace Invalid Values 
# step 7 : Replace common invalid values with NaN
df.replace(['N/A','NULL',''],np.nan,inplace = True)

In [17]:
# Remove Extra Spaces 
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [19]:
# Standaridize Text Format
# Convert text into power case
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [ ]:
# Validate Email Address
df = df[df['Email'].str.contains('@',na = False)]

In [21]:
# Convert Date Column type
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors = 'coerce') # NAT
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], errors = 'coerce')

In [23]:
# Convert Numeric Columns
cols = ['Qty','Unit_Price','Discount']
for c in cols :
    df[c] = pd.to_numeric(df[c], errors = 'coerce')

In [24]:
# Remove Invalid Quantity
# Remove records having -ve or 0
df= df[df['Qty']>0]

In [26]:
# Fill Missing Values
df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\918669690.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discount'] = df['Discount'].fillna(0)
C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\918669690.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Phone'] = df['Phone'].fillna('Unknown')
C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\918669690.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [27]:
# Feature Engineering 
# Add Total Sales Column
df['Sales'] = df['Qty'] * df['Unit_Price']

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\3906474291.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales'] = df['Qty'] * df['Unit_Price']

In [28]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-06-30,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-03,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-06,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0

In [29]:
# Net Amount 
df['Net_Amount'] = df['Sales'] - (df['Sales']*df['Discount']/100)

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\822696575.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net_Amount'] = df['Sales'] - (df['Sales']*df['Discount']/100)

In [30]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-06-30,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-03,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-06,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-03-03,2997.0,2997.0

In [31]:
df['Profit'] = df['Net_Amount'] * 0.20

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\1612685949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Net_Amount'] * 0.20

In [32]:
df['Month'] = df['Order_Date'].dt.month_name()

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\1885520962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month_name()

In [33]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-06-30,7996.0,7996.0,1599.2,June
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-03,24995.0,24995.0,4999.0,February
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-06,5997.0,5997.0,1199.4,May
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,299.4,February
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.0,599.6,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN,NaN,April
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.0,599.4,January
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-03-03,2997.0,2997.0,599.4,March

In [36]:
df['year'] = df['Order_Date'].dt.year

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\1057815667.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['Order_Date'].dt.year

In [37]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-06-30,7996.0,7996.0,1599.2,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-03,24995.0,24995.0,4999.0,February,2025.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-06,5997.0,5997.0,1199.4,May,2025.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,299.4,February,2025.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February,2025.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.0,599.6,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN,NaN,April,2025.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.0,599.4,January,2025.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-03-03,2997.0,2997.0,599.4,March,2025.0

In [43]:
df['Weekday'] = df['Order_Date'].dt.day_name()

In [41]:
df = df.drop(columns='Weekday')

In [44]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-06-30,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,0.0,Card,Pending,2025-02-03,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,0.0,COD,Returned,2025-05-06,5997.0,5997.0,1199.4,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,299.4,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.0,7999.2,February,2025.0,Monday
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,NaT,2998.0,2998.0,599.6,NaN,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN,NaN,April,2025.0,Thursday
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-11,2997.0,2997.0,599.4,January,2025.0,Saturday
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,0.0,COD,Cancelled,2025-03-03,2997.0,2997.0,599.4,March,2025.0,Monday

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       393 non-null    object
 1   Order_Date     345 non-null    datetime64[ns]
 2   Customer_Name  393 non-null    object
 3   Email          393 non-null    object
 4   Phone          393 non-null    object
 5   City           393 non-null    object
 6   State          393 non-null    object
 7   Product        393 non-null    object
 8   Category       393 non-null    object
 9   Qty            393 non-null    float64
 10  Unit_Price     355 non-null    float64
 11  Discount       393 non-null    float64
 12  Payment_Mode   393 non-null    object
 13  Order_Status   393 non-null    object
 14  Delivery_Date  345 non-null    datetime64[ns]
 15  Sales          355 non-null    float64
 16  Net_Amount     355 non-null    float64
 17  Profit         355 non-null    float64
 18  Month          345 non-null    object
 19  year           345 non-null    float64
 20  Weekday        345 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 67.5+ KB

In [46]:
df.isnull().sum()

Order_ID          0
Order_Date       48
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       38
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    48
Sales            38
Net_Amount       38
Profit           38
Month            48
year             48
Weekday          48
dtype: int64

In [47]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,year
count,345,393.000000,355.000000,393.0,345,355.000000,355.000000,355.000000,345.0
mean,2025-04-03 03:32:52.173913088,3.325700,3259.845070,0.0,2025-04-03 03:32:52.173913088,11114.138028,11114.138028,2222.827606,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.0,2025-01-01 00:00:00,499.000000,499.000000,99.800000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.0,2025-02-14 00:00:00,2599.000000,2599.000000,519.800000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,0.0,2025-04-05 00:00:00,5997.000000,5997.000000,1199.400000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,0.0,2025-05-16 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,0.0,2025-06-30 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.467601,3034.735697,0.0,NaN,12227.528790,12227.528790,2445.505758,0.0

In [49]:
df.to_csv('Clean_Ecommerce.csv',index = False)

In [50]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\harsh\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\harsh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [57]:
# Import Data into MySql
from sqlalchemy import create_engine, text

engine = create_engine(
    "mssql+pyodbc://@localhost/ecommerce?"
    "trusted_connection=yes&"
    "driver=ODBC+Driver+18+for+SQL+Server&"
    "Encrypt=Optional&"
    "TrustServerCertificate=yes"
)

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            @@SERVERNAME AS server_name,
            DB_NAME() AS database_name,
            SYSTEM_USER AS login_name
    """))
    print(result.fetchone())

('LAPTOP-PLPC9QC8', 'ecommerce', 'LAPTOP-PLPC9QC8\\Harsh')

C:\Users\Harsh\AppData\Local\Temp\ipykernel_13064\2112171790.py:12: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  with engine.connect() as connection:

In [58]:
df.to_sql(
    name='orders',
    con=engine,
    schema='dbo',
    if_exists='replace',
    index=False
)

96

In [60]:
df.shape

(393, 21)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 393 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       393 non-null    object
 1   Order_Date     345 non-null    datetime64[ns]
 2   Customer_Name  393 non-null    object
 3   Email          393 non-null    object
 4   Phone          393 non-null    object
 5   City           393 non-null    object
 6   State          393 non-null    object
 7   Product        393 non-null    object
 8   Category       393 non-null    object
 9   Qty            393 non-null    float64
 10  Unit_Price     355 non-null    float64
 11  Discount       393 non-null    float64
 12  Payment_Mode   393 non-null    object
 13  Order_Status   393 non-null    object
 14  Delivery_Date  345 non-null    datetime64[ns]
 15  Sales          355 non-null    float64
 16  Net_Amount     355 non-null    float64
 17  Profit         355 non-null    float64
 18  Month          345 non-null    object
 19  year           345 non-null    float64
 20  Weekday        345 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 67.5+ KB

In [62]:
df['Order_ID'].isna().sum()

np.int64(0)

In [63]:
(df['Order_ID'].astype(str).str.strip() == '').sum()

np.int64(6)